# Generated by Django 5.2.5 on 2025-09-02 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab', 'Lab Tech'), ('pharmacist', 'Pharmacist'), ('other', 'Other')], max_length=30)),
                ('service_location', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practitionerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
